name: add SAST

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  secrets-scan:
    name: Secrets Scan (Gitleaks Full)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
      - name: Run Gitleaks Full Scan
        run: |
          gitleaks detect --source . -v --exit-code 2

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build application
        run: mvn -B -DskipTests clean package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare empty reports
        run: |
          echo '{"version":"2.1.0","results":[]}' > semgrep.json
          echo "Semgrep SAST Report" > semgrep.txt
          echo '{}' > semgrep.sarif
      - name: Install Semgrep
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install semgrep
      - name: Run Semgrep scan
        run: |
          source venv/bin/activate
          semgrep scan --config auto --json --output semgrep.json || true
          semgrep scan --config auto --text --output semgrep.txt || true
          semgrep scan --config auto --sarif --output semgrep.sarif || true
      - name: Upload Semgrep reports
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: |
            semgrep.json
            semgrep.txt
            semgrep.sarif

  sca:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.9.11-eclipse-temurin-21-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run OWASP
        run: mvn -B org.owasp:dependency-check-maven:check -Dnvd.api.key=${{ secrets.NVD_API_KEY }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

  dast-and-fuzzing:
    name: DAST and Fuzzing Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write
      actions: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: target
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Start Application
        run: |
          nohup java -jar target/*.jar &
          sleep 30
      - name: Fix permissions
        run: chmod -R 777 .
      - name: Create Empty Rules File
        run: touch zap_rules.tsv && chmod 666 zap_rules.tsv
      - name: Pull ZAP Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: ZAP Baseline Scan (DAST)
        run: |
          docker run --rm --network host --user root \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:8080 -r zap-baseline-report.html -I || true

      - name: ZAP API Fuzzing Scan
        run: |
          docker run --rm --network host --user root \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-api-scan.py -t http://localhost:8080/v3/api-docs -f openapi -r zap-fuzz-report.html -I || true

      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-baseline-report.html
            zap-fuzz-report.html